name: fonction testRep2 return 2
on: [push]
jobs:
    phpunit:
        name: PHPUnit
        runs-on: 'ubuntu-latest'

        steps:
            -   run: echo "début du test"
            -   uses: actions/checkout@v1

            -   name: Run composer install
                run: composer install --no-progress --no-suggest

            -   name: Run PHPUnit
                run: php bin/phpunit
