name: fonction testRep2 return 2
on: [push]
jobs:
    phpunit:
        name: PHPUnit
        runs-on: 'ubuntu-latest'

        steps:
            -   name: Setup PHP
                uses: actions/checkout@v1
                with:
                    php-version: '8.1'

            -   name: Run composer install
                run: composer install --no-progress --no-suggest

            -   name: Run PHPUnit
                run: php bin/phpunit
